version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - postgres
      - vite
    networks:
      - webapp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
    ports:
      - "9001:9000"
    networks:
      - webapp

  vite:
    image: node:18-alpine
    container_name: ${APP_NAME}_vite
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
      - "5174:5174"
    networks:
      - webapp    

  postgres:
    image: postgres:12.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: proprli-db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - webapp

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - webapp

networks:
  webapp:
    driver: bridge
